(function() {var implementors = {};
implementors["infinity"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/core/struct.Context.html\" title=\"struct infinity::core::Context\">Context</a>",synthetic:false,types:["infinity::core::Context"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/memory/struct.RegionToken.html\" title=\"struct infinity::memory::RegionToken\">RegionToken</a>",synthetic:false,types:["infinity::memory::RegionToken"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/memory/struct.Buffer.html\" title=\"struct infinity::memory::Buffer\">Buffer</a>",synthetic:false,types:["infinity::memory::Buffer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/memory/struct.UnsafeBuffer.html\" title=\"struct infinity::memory::UnsafeBuffer\">UnsafeBuffer</a>",synthetic:false,types:["infinity::memory::UnsafeBuffer"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/queues/struct.QueuePair.html\" title=\"struct infinity::queues::QueuePair\">QueuePair</a>&lt;'a&gt;",synthetic:false,types:["infinity::queues::QueuePair"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"infinity/queues/struct.QueuePairFactory.html\" title=\"struct infinity::queues::QueuePairFactory\">QueuePairFactory</a>&lt;'a&gt;",synthetic:false,types:["infinity::queues::QueuePairFactory"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
